#############################################################################
#
# Project Makefile
#
# (c) Wouter van Ooijen (www.voti.nl) 2016
#
# This file is in the public domain.
# 
#############################################################################

# source files in this project (main.cpp is automatically assumed)
SOURCES := circle.cpp ball.cpp drawable.cpp filled_rectangle.cpp line.cpp rectangle.cpp vector.cpp wall.cpp window.cpp victim.cpp

# header files in this project
HEADERS := circle.hpp ball.hpp drawable.hpp filled_rectangle.hpp line.hpp rectangle.hpp vector.hpp wall.hpp window.hpp victim.hpp

# other places to look for files for this project
SEARCH  := 

# set RELATIVE to the next higher directory 
# and defer to the Makefile.* there
RELATIVE := ..
include $(RELATIVE)/Makefile.native
